// cc -O3 0001-one-big-manager-or-many-small-ones.c
// The output looks like this:
// BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
// BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBSSSSSBBBBBBBBBBBBBBBBBBBBBBBB
// BBBBBBBBBSSBBBBBBBSSSSSSBBBBBBBBBBBSSSSSSSSSSSSSSSBBBBBBBBBBBBB
// BBBBBBBBBBBBBBBBBBBBBBBBBSBBBBBBBSSSSSSSBBBBBSSSSSSSSSSSSSBBBBB
// BBBBBSBBBBSSSBBBBBBSSSSSSSSBBBBBBBBBBBSSSSSSSSSSSSSSSSSSBBBBBBB
// BBBBSBBBBSSSBBBBBSSSSSSSSBBBBBBBBBBSSSSSSSSSSSSSSSSBBBBBBBBBBBB
// BBBBBBBBSSBBBBBBSSSSSSBBBBBBBBBBBSSSSSSSSSSSSSBBBBBBBBBBBBBBBBB
// BBBBBBBBBBBBBBBBBBBBBBBBSSSSBBBBBSSSSSSSBBBBSSSSSSSSSSSSSSSSBBB
// BBBBBBBBBBSSSSBBBBBBSSSSSSSSSBBBBBBBBBBBSSSSSSSSSSSSSSSSSSSBBBB
// BBBBBSBBBSSSSBBBBBBSSSSSSSSSBBBBBBBBBBSSSSSSSSSSSSSSSSSSBBBBBBB
// BBBBSBBBBSSSBBBBBBSSSSSSSSBBBBBBBBBBSSSSSSSSSSSSSSSSSSBBBBBBBBB
// BBBBSBBBBSSSBBBBBSSSSSSSSBBBBBBBBBBSSSSSSSSSSSSSSSSBBBBBBBBBBBB
// BBBBBBBBSSSBBBBBBSSSSSSBBBBBBBBBBBSSSSSSSSSSSSSSBBBBBBBBBBBBBBB
// BBBBBBBBSSBBBBBBSSSSSSBBBBBBBBBBBSSSSSSSSSSSSSBBBBBBBBBBBBBBBBB
// BBBBBBBBBBBBBBBBSSSSSBBBBBBBBBBBSSSSSSSSSSSBBBBBBBBBBBBBBBBBBBB
// BBBBBBBBBBBBBBBBBSBBBBBSSSSSSBBBBSSSSSSSBBBBSSSSSSSSSSSSSSSSBBB
// BBBBBBBBBBBSSSBBBBBBBSSSSSSSSSBBBBBBBBBBBSSSSSSSSSSSSSSSSSSSSBB
// BBBBBBBBBBSSSSBBBBBBSSSSSSSSSBBBBBBBBBBBSSSSSSSSSSSSSSSSSSSSBBB
// BBBBBSBBBBSSSBBBBBBSSSSSSSSSBBBBBBBBBBSSSSSSSSSSSSSSSSSSSSBBBBB
// BBBBBSBBBSSSSBBBBBBSSSSSSSSSBBBBBBBBBSSSSSSSSSSSSSSSSSSSSBBBBBB
// BBBBBSBBBSSSSBBBBBSSSSSSSSSBBBBBBBBBBSSSSSSSSSSSSSSSSSSBBBBBBBB
// BBBBSBBBBSSSBBBBBBSSSSSSSSBBBBBBBBBBSSSSSSSSSSSSSSSSSSBBBBBBBBB
// BBBBSBBBBSSSBBBBBBSSSSSSSBBBBBBBBBBSSSSSSSSSSSSSSSSSBBBBBBBBBBB
// BBBBSBBBBSSSBBBBBSSSSSSSSBBBBBBBBBBSSSSSSSSSSSSSSSSBBBBBBBBBBBB
// BBBBBBBBSSSBBBBBBSSSSSSSBBBBBBBBBBSSSSSSSSSSSSSSSSBBBBBBBBBBBBB
// BBBBBBBBSSSBBBBBBSSSSSSSBBBBBBBBBBSSSSSSSSSSSSSSBBBBBBBBBBBBBBB
// BBBBBBBBSSBBBBBBBSSSSSSBBBBBBBBBBSSSSSSSSSSSSSSBBBBBBBBBBBBBBBB
// BBBBBBBBSSBBBBBBSSSSSSBBBBBBBBBBBSSSSSSSSSSSSSBBBBBBBBBBBBBBBBB
// BBBBBBBBSBBBBBBBSSSSSBBBBBBBBBBBBSSSSSSSSSSSSBBBBBBBBBBBBBBBBBB
// BBBBBBBBBBBBBBBBSSSSSBBBBBBBBBBBSSSSSSSSSSSBBBBBBBBBBBBBBBBBBBB
// BBBBBBBBBBBBBBBBSSSSBBBBBBBBBBBBSSSSSSSSSSBBBBBSSSSSSSSBBBBBBBB
// BBBBBBBBBBBBBBBBBSBBBBBSSSSSSBBBBSSSSSSSBBBBSSSSSSSSSSSSSSSSSBB
// BBBBBBBBBBBBSSBBBBBBBBSSSSSSSSBBBBSSSSBBBBSSSSSSSSSSSSSSSSSSSSB
// BBBBBBBBBBBSSSBBBBBBBSSSSSSSSSBBBBBBBBBBBSSSSSSSSSSSSSSSSSSSSBB
// It takes too long to finish executing on my MacBook, so I interrupt it.
// The "B" and "S" is almost equal, so it's not matter to use one big manager
// or many small ones.
#include <stdio.h>
#include <stdlib.h>
#include <time.h>

int f(x)
{
  int m = 0x1;
  while (m < x)
  {
    m <<= 1;
  }
  return m;
}

const int N = 1 << 16;

int test(int k_max, int n_max)
{
  int one_big = 0;
  for (int i = 0; i < N; i++)
  {
    int k     = rand() % k_max;
    int f_sum = 0, n_sum = 0;
    for (int j = 0; j < k; j++)
    {
      int nj = rand() % n_max + 1;
      n_sum += nj;
      f_sum += f(nj);
    }
    if (f(n_sum) >= f_sum)
    {
      one_big++;
    }
  }
  return one_big;
}

int main()
{
  for (int k = 32; k < 2048; k += 32)
  {
    for (int n = 2; n < 128; n += 2)
    {
      int big_count = 0, small_count = 0;
      for (int i = 0; i < 8; i++) {
        int one_big = test(k, n);
        big_count += one_big > N - one_big;
        small_count += one_big < N - one_big;
        if (big_count == 4) {
          printf("B");
          break;
        } else if (small_count == 4) {
          printf("S");
          break;
        }
      }
    }
    printf("\n");
  }
}
